<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{useRoute,useRouter}from'vue-router';import{ElMessage}from'element-plus';import{api}from'../api/client';import type{Author,Book,Tag}from'../types/book';
const route=useRoute(),router=useRouter();const loading=ref(true),saving=ref(false);const authors=ref<Author[]>([]),tags=ref<Tag[]>([]),cover=ref<File>();const form=reactive({title:'',subtitle:'',description:'',language:'',publisher:'',isbn:'',reading_status:'unread',rating:0,author_ids:[]as string[],tag_ids:[]as string[]});
async function load(){loading.value=true;try{const[b,a,t]=await Promise.all([api.get<Book>(`/books/${route.params.id}`),api.get<Author[]>('/authors'),api.get<Tag[]>('/tags')]);const book=b.data;Object.assign(form,{title:book.title,subtitle:book.subtitle,description:book.description,language:book.language,publisher:book.publisher,isbn:book.isbn,reading_status:book.reading_status,rating:book.rating,author_ids:book.authors.map(x=>x.id),tag_ids:book.tags.map(x=>x.id)});authors.value=a.data;tags.value=t.data}finally{loading.value=false}}
function chooseCover(e:Event){cover.value=(e.target as HTMLInputElement).files?.[0]}
async function save(){if(!form.title.trim()){ElMessage.error('书名不能为空');return}saving.value=true;try{await api.put(`/books/${route.params.id}`,form);if(cover.value){const data=new FormData();data.append('cover',cover.value);await api.post(`/books/${route.params.id}/cover`,data)}ElMessage.success('书籍已更新');await router.push(`/books/${route.params.id}`)}catch(e:any){ElMessage.error(e.response?.data?.error||'保存失败')}finally{saving.value=false}}
onMounted(load)
</script>
<template><section v-loading="loading"><el-page-header @back="$router.push(`/books/${$route.params.id}`)" title="返回详情"/><el-card><h1>编辑书籍</h1><el-form label-position="top"><div class="columns"><el-form-item label="书名" required><el-input v-model="form.title"/></el-form-item><el-form-item label="副标题"><el-input v-model="form.subtitle"/></el-form-item><el-form-item label="作者"><el-select v-model="form.author_ids" multiple filterable clearable><el-option v-for="a in authors" :key="a.id" :label="a.name" :value="a.id"/></el-select></el-form-item><el-form-item label="标签"><el-select v-model="form.tag_ids" multiple filterable clearable><el-option v-for="t in tags" :key="t.id" :label="t.name" :value="t.id"/></el-select></el-form-item><el-form-item label="语言"><el-input v-model="form.language"/></el-form-item><el-form-item label="出版社"><el-input v-model="form.publisher"/></el-form-item><el-form-item label="ISBN"><el-input v-model="form.isbn"/></el-form-item><el-form-item label="阅读状态"><el-select v-model="form.reading_status"><el-option label="未读" value="unread"/><el-option label="在读" value="reading"/><el-option label="已读" value="finished"/><el-option label="暂停" value="paused"/><el-option label="弃读" value="abandoned"/></el-select></el-form-item><el-form-item label="评分"><el-rate v-model="form.rating" clearable/></el-form-item><el-form-item label="更换封面"><input type="file" accept="image/jpeg,image/png,image/webp" @change="chooseCover"/></el-form-item></div><el-form-item label="简介"><el-input v-model="form.description" type="textarea" :rows="7"/></el-form-item><el-button type="primary" :loading="saving" @click="save">保存</el-button></el-form></el-card></section></template>
<style scoped>.el-card{max-width:900px;margin:2rem auto}.columns{display:grid;grid-template-columns:1fr 1fr;gap:0 1.5rem}.el-select{width:100%}@media(max-width:650px){.columns{grid-template-columns:1fr}}</style>
