<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import{api}from'../api/client';import type{Author,Tag}from'../types/book';const authors=ref<Author[]>([]),tags=ref<Tag[]>([]),loading=ref(true);const author=reactive({id:'',name:'',sort_name:''}),tag=reactive({id:'',name:''});const authorDialog=ref(false),tagDialog=ref(false);
async function load(){loading.value=true;try{[authors.value,tags.value]=await Promise.all([api.get<Author[]>('/authors').then(r=>r.data),api.get<Tag[]>('/tags').then(r=>r.data)])}finally{loading.value=false}}
function addAuthor(){Object.assign(author,{id:'',name:'',sort_name:''});authorDialog.value=true}function editAuthor(a:Author){Object.assign(author,a);authorDialog.value=true}async function saveAuthor(){if(!author.name.trim())return;author.id?await api.put(`/authors/${author.id}`,author):await api.post('/authors',author);authorDialog.value=false;ElMessage.success('作者已保存');await load()}
async function deleteAuthor(a:Author){await ElMessageBox.confirm(`删除作者“${a.name}”并解除其书籍关联？`,'确认删除',{type:'warning'});await api.delete(`/authors/${a.id}`);ElMessage.success('作者已删除');await load()}
function addTag(){Object.assign(tag,{id:'',name:''});tagDialog.value=true}function editTag(t:Tag){Object.assign(tag,t);tagDialog.value=true}async function saveTag(){if(!tag.name.trim())return;tag.id?await api.put(`/tags/${tag.id}`,tag):await api.post('/tags',tag);tagDialog.value=false;ElMessage.success('标签已保存');await load()}
async function deleteTag(t:Tag){await ElMessageBox.confirm(`删除标签“${t.name}”并解除其书籍关联？`,'确认删除',{type:'warning'});await api.delete(`/tags/${t.id}`);ElMessage.success('标签已删除');await load()}
onMounted(load)
</script>
<template><section v-loading="loading"><h1>作者与标签</h1><div class="panels"><el-card><template #header><div class="head"><strong>作者</strong><el-button size="small" type="primary" @click="addAuthor">新增作者</el-button></div></template><el-table :data="authors"><el-table-column prop="name" label="姓名"/><el-table-column prop="sort_name" label="排序名"/><el-table-column width="140" label="操作"><template #default="s"><el-button link type="primary" @click="editAuthor(s.row)">编辑</el-button><el-button link type="danger" @click="deleteAuthor(s.row)">删除</el-button></template></el-table-column></el-table></el-card><el-card><template #header><div class="head"><strong>标签</strong><el-button size="small" type="primary" @click="addTag">新增标签</el-button></div></template><el-table :data="tags"><el-table-column prop="name" label="名称"/><el-table-column width="140" label="操作"><template #default="s"><el-button link type="primary" @click="editTag(s.row)">编辑</el-button><el-button link type="danger" @click="deleteTag(s.row)">删除</el-button></template></el-table-column></el-table></el-card></div><el-dialog v-model="authorDialog" :title="author.id?'编辑作者':'新增作者'" width="420"><el-form label-position="top"><el-form-item label="姓名" required><el-input v-model="author.name"/></el-form-item><el-form-item label="排序名"><el-input v-model="author.sort_name"/></el-form-item></el-form><template #footer><el-button @click="authorDialog=false">取消</el-button><el-button type="primary" @click="saveAuthor">保存</el-button></template></el-dialog><el-dialog v-model="tagDialog" :title="tag.id?'编辑标签':'新增标签'" width="420"><el-form label-position="top"><el-form-item label="名称" required><el-input v-model="tag.name"/></el-form-item></el-form><template #footer><el-button @click="tagDialog=false">取消</el-button><el-button type="primary" @click="saveTag">保存</el-button></template></el-dialog></section></template>
<style scoped>.panels{display:grid;grid-template-columns:1fr 1fr;gap:1.5rem}.head{display:flex;align-items:center;justify-content:space-between}@media(max-width:800px){.panels{grid-template-columns:1fr}}</style>
